bmw_main:
    resource: "@BmwMainBundle/Controller/"
    type:     annotation
    prefix:   /

movie_show:
     path:   /movie/{page}
     defaults:  { _controller: BmwMainBundle:DashBoard:movie }


movie_select:
     path:   /movies/{type}
     defaults:  { _controller: BmwMainBundle:DashBoard:select }

user:
    path:    /user
    defaults:  { _controller: BmwMainBundle:User:user }

login:
    path:   /login
    defaults: { _controller: BmwMainBundle:Login:login}

logout:
     path:   /logout
     defaults: { _controller: BmwMainBundle:Login:logout}

movie_review:
    path: /movie/{page}/review/
    defaults: { _controller: BmwMainBundle:AddReview:addreview }

