bmw_main:
    resource: "@BmwMainBundle/Controller/"
    type:     annotation
    prefix:   /

movie_show:
     path:   /movie/{page}
     defaults:  { _controller: BmwMainBundle:DashBoard:movie }


movie_select:
     path:   /movies/{type}
     defaults:  { _controller: BmwMainBundle:DashBoard:select }